# Run these command before start service 
# sudo chown -R 1000:1000 etc data log
# sudo chmod -R 770 etc data log

services: 
  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.1
    restart: unless-stopped
    environment: 
    - EMQX_NAME=emqx
    - EMQX_CLUSTER__DISCOVERY=static
    - EMQX_LOADED_PLUGINS="emqx_auth_mnesia,emqx_prometheus"
    ports:
      - 1883:1883
      - 18083:18083
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ./emqx/log:/opt/emqx/log
      - ./emqx/etc:/opt/emqx/etc
      - ./emqx/data:/opt/emqx/data 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      tig-network: 
        ipv4_address: 192.168.1.1

networks:
  tig-network:
    external:
      name: tig-network
